### ISSUE TITLE
Filter not working after map pan/zoom

### ISSUE THREAD

**Issue by cascafico** [umap-project/umap#1005]
I set up a filter on some fields. It works both in data list and map, but after a pan or zoom, all unfiltered and filtered objects appear in map, while data list remains ok (only filtered).

Example
https://umap.openstreetmap.fr/it/map/prezzi-carburanti_771172
try to apply filter ie: "1.7", look the map and pan a little

**Comment by yohanboniface** [comment]
Confirmed.

**Comment by yohanboniface** [comment]
@cascafico this issue appears when using remote data layer with in dynamic mode. In your case, I think you can uncheck "Dynamic". This option is only useful when passing the map center/bbox to the remote server in order to adapt the returned data, which is not the case for you, AFAIK.

I'll see anyway how to fix this edge case. Thanks for the report with a reproductible case! :)
