### ISSUE TITLE
Location does not work on macOS with Safari

### ISSUE THREAD

**Issue by fxcoudert** [umap-project/umap#1073]
With latest Safari (16.4) on latest macOS (13.3.1):

- I open a map, let's say https://umap.openstreetmap.fr/fr/map/fete-du-phare-du-cordouan_737137#14/45.6190/-1.0278
- I ask the to center on my position
- Nothing happens… I do not get asked for permission (other apps, like Google Maps, do that) and the button stays "pressed":
![Capture d’écran 2022-06-08 à 16 08 08](https://user-images.githubusercontent.com/1980544/172637771-f6ac7763-642b-4b7b-b589-4611a9dcd03b.png)

**Comment by davidbgk** [comment]
I can reproduce, it looks to be because the IGN logo is served with http (not https) hence the mixed content error:

<img width="1432" alt="Capture d’écran, le 2023-05-01 à 11 30 39" src="https://user-images.githubusercontent.com/3556/235478298-1d7597f1-ce87-43c4-ab02-8c3f4d329eef.png">

<img width="920" alt="Capture d’écran, le 2023-05-01 à 11 32 14" src="https://user-images.githubusercontent.com/3556/235478494-7a3cf789-104e-4432-84e9-87b7b78092b0.png">

**Comment by fxcoudert** [comment]
The same asset can be served over HTTPS at 
https://wxs.ign.fr/static/logos/IGN/IGN.gif

**Comment by davidbgk** [comment]
@fxcoudert ça devrait être corrigé d'après mes tests, je te laisse fermer si tu arrives à vérifier le correctif.

**Comment by fxcoudert** [comment]
C'est bon de mon côté.
