### ISSUE TITLE
 Server error with certain OSM Login (again)

### ISSUE THREAD

**Issue by bagage** [umap-project/umap#1237]
Very similar to https://github.com/umap-project/umap/issues/1202, I cannot log in anymore via OSM OAuth. It might also be related to https://github.com/umap-project/umap/issues/962#event-9418314884 (because I was the original author on this one and I did rename my OSM account a while ago).

Sometime I get a `Oops, Server error…` immediately when clicking on OSM link. Sometime it's when coming back from OSM.org auth page. 

PS: is there any alerting/reporting tooling when 5xx server errors are happening? That would help to give all the required context I hope to solve that - otherwise I can provide extra info if needed.

**Comment by yohanboniface** [comment]
Yes, I need more context: I need your OSM username and your current uMap one (which is the old OSM one).

The issue is well known, but not easy to fix: when someone login with a username that already exists but with another provider, we cannot create it (username must be unique, given it's used in URL, and IIRC it's a Django constraint), and we have no way to merge the two accounts, given we do not have emails, which would be the only way to be sure that two accounts are from the same person.
The fix is something around:
- display the provider to the user in uMap "My Dashboard"
- either user to attach another provider while being already logged in / or allow the user to change their username, and thus when a "duplicate" account is created, add whatever random string to the username to prevent the clash (we used to do that, but people complained that changing their username in OSM was not reflected in uMap)

In the meantime, I fix by hand the case that are reported to me, which is far from ideal…

**Comment by bagage** [comment]
OK very clear, thanks @yohanboniface. Maybe this is a super specific bug (only for existing UMap users that renamed their third party account) and it's fine like this. BTW my name was `Gautier PP` (or `GautierPP`) and now is `bagage` :).

Since solving the root issue might be too tricky; would it be possible to catch this specific 502 error, and display a specific error page with the explanation you provided here? Like `It seems a user already exists with this identifier. This is a known [issue](https://github.com/umap-project/umap/issues/1237#issuecomment-1657669077) - please contact us to unblock your account` or something along these lines? :)

**Comment by yohanboniface** [comment]
@bagage should be good now, sorry for the lag!

**Comment by bagage** [comment]
Yes all good, thanks @yohanboniface!

**Comment by yohanboniface** [comment]
This should be "fixed" since 1.6.0: username is no more updated at login, but user can change their username through this new page umap.openstreetmap.fr/fr/me/profile
