### ISSUE TITLE
Draw circles or adding icons to put circles

### ISSUE THREAD

**Issue by yohanboniface** [umap-project/umap#172]
Originally reported by: **BitBucket: [mmeinert](http://bitbucket.org/mmeinert), GitHub: [mmeinert](http://github.com/mmeinert)**

---

I'd like to have circles on a map but I as I can understand it's complicated because of the calculation it supposes.

My alternate solution is to have a library of 4 "markers" with defined radius (50m/100m/150m/200m) to put on a map. Size should of course be relative to the zoom level.

Also, I found [this](http://gis.stackexchange.com/questions/126917/leaflet-draw-get-circle-extent/127123#127123) but I don't know if its really relevant in this case 

---
- Bitbucket: https://bitbucket.org/yohanboniface/umap/issue/172

**Comment by adrien-github** [comment]
Hi,
I am interested by this functionality for my Beehives : The bees can fly up to 3km to harvest nectar and pollen.
I would like to draw a map with my beehives and a circle with a radius of 3km, to know where they can find food and also chemicals unfortunately. Ideally I would like to add a gradient of color, because they fly much more near the beehive than at 3km, but maybe it too complicated.

So if you add markers, could you please add a 3km markers ?

Thanks you very much for your software.

**Comment by yohanboniface** [comment]
Closing in favour of #835
