### ISSUE TITLE
Problem in the response - CORS error (new since a few days)

### ISSUE THREAD

**Issue by Wikinaut** [umap-project/umap#1793]
![grafik](https://github.com/umap-project/umap/assets/1151915/e91336cc-7bee-4e5f-8026-17d700e6a853)

**Comment by Wikinaut** [comment]
![grafik](https://github.com/umap-project/umap/assets/1151915/9e75a619-0728-42f5-9403-43c2db1b0b17)

**Comment by yohanboniface** [comment]
Hi @Wikinaut 

The error you point to in the console is unrelated, it's the Sentry call that is blocked by your browser. Sentry is an anonymous error tracker, that help us get more context when an error occurs.

If I load your map, I see errors for three datalayers:

![image](https://github.com/umap-project/umap/assets/146023/c73b372f-0da2-41b0-9f83-e53671a5f768)

The first and the third are datalayers URL with old (< 1 month ago) schema. Those URLs should have been replaced by new ones during the migration, but obviously are not in this case. Has this map been imported recently, which could explain ?

The second one point to a missing file in the server. The server is looking at the file `my-data.geojson`, on a very old map. This file name is a very old pattern (from years ago), and is missing since #1003. The datalayer is "Kiezblock politisch beschlossen". Is this layer supposed to point on a file that old ?
