### ISSUE TITLE
Export and import of gpx is inconsistent

### ISSUE THREAD

**Issue by Spielmops** [umap-project/umap#1932]
I create an item in a map-layer:
![testdaten nach Eingabe](https://github.com/umap-project/umap/assets/3194177/accc6b42-65ff-4bf6-800d-ea009dcaa4be)

Then I export this item as gpx and look at it via editor:
![Testdaten als GPX-Datei](https://github.com/umap-project/umap/assets/3194177/cb6ec162-a107-4072-9b34-a60431ac8754)

And after that I import this file. Result:
![Testdaten als GPX-Import](https://github.com/umap-project/umap/assets/3194177/d9ef04c0-76e3-46dc-84f8-499c8f6fe4f4)

Why is this so? Why is the description not in description-field any more?

Spielmops

**Comment by yohanboniface** [comment]
Thanks for the report!

Not sure exactly about the status of the external lib we current use for exporting to gpx: https://github.com/tyrasd/togpx
See also https://github.com/pnlabs/togpx/pull/1 on this topic

Needs more investigation!

**Comment by yohanboniface** [comment]
Maybe switch to https://github.com/We-Gold/gpxjs ?

**Comment by yohanboniface** [comment]
From the togpx doc:

> By default, the desc tag of GPX elements will be constructed by concatenating all respective GeoJSON properties.

So this is the expected behaviour. It's configurable, but from the [specs](https://www.topografix.com/GPX/1/1/#type_trkType) it seems there is no way to have custom properties, only desc is expected (if I read it correctly). So we can either keep the current behaviour, so all properties are exported in the GPX, either have a custom configuration to export only the `description` field into `desc`.

First thing to decide: I wonder how other GPX tools behave, and specifically how other tools would load a GPX concatenating many properties in the `desc` field.

**Comment by Spielmops** [comment]
> I would say the = within the description is unfortunate.

Even if I reduce <desc> in that gpx-file to 
`<desc>Und hier steht die Beschreibung des betreffenden Objektes.</desc>`
the content of `<desc></desc>` is not imported to "description", where I expect it.

Spielmops

**Comment by yohanboniface** [comment]
A new release has been deployed just now that changes the lib used for GPX. Could have a try ?

**Comment by yohanboniface** [comment]
Closing as this should be fixed with the latest release. Please reopen if it's not!

**Comment by Spielmops** [comment]
Sorry for the late answer, if been in hospital,

I tried again:
- export to gpx: file-content looks good, it's pure gpx
- import is not ok: the description is not imported to the description-field but a new data-field "desc" is created with that content.

Thats not, what I expect, sorry ...

Spielmops
