### ISSUE TITLE
Emptying data from map settings deletes all layers

### ISSUE THREAD

**Issue by Hedaja** [umap-project/umap#1934]
**Describe the bug**
When data gets emptied through the map settings menu, all layers are deleted as well.

**To Reproduce**
1. Go to any map (for example https://umap.openstreetmap.de/en/map/test-layer-selction-hidden-layer_61300)
2. Click on Edit
3. Click on Map Advanced Properties
4. open Advanced Actions and click Empty
5. All layers are getting completely erased

**Expected behavior**
Keep layers but delete all data (points/lines/areas) within them.

**Comment by almet** [comment]
Hi, and thanks for taking the time to open an issue. We've just had a look and cannot find the button you're talking about (I don't see an "Empty" button or link).

Do you see the same thing as this screen capture shows? If not, could you please share a capture as well? 

![image](https://github.com/umap-project/umap/assets/67073/6c76f945-3a83-4906-accd-d87193de8d2a)

It can also be because of the translation, or the naming choice on our side, do you think the label is explicit enough? :thinking:

**Comment by Hedaja** [comment]
That's strange. I actually have more options displayed (no matter if German or English interface).
![grafik](https://github.com/umap-project/umap/assets/693781/4ef5397a-0e05-4aaf-b356-585851c4f8f4)
Maybe I see more because I am the owner of map. I tried to set full permissions to all other users as well though.

The German umap instance is running umap 2.4.0 by the way.

**Comment by almet** [comment]
Hey, just found the button you're talking about, and have been able to reproduce locally.

![image](https://github.com/umap-project/umap/assets/67073/679473a6-7d4c-4df7-8d32-4808a4a8a94b)

(At least the button is here).

Tagging @davidbgk and @yohanboniface if they want to chime in, as we had a redesign of the datalayer explorer lately (it might be related). FWIW, I've checked and it doesn't seem related to the syncing changes.

**Comment by yohanboniface** [comment]
No, nothing to do with recent changes imho. This seems the expected behaviour (the button calls the `Map.empty` method), but this behaviour could obviously be challenged. Specifically as we also have a "delete all layers" button.

Let's have two methods, one to empty the datalayers (but keep them), and the other on to delete the layers and data.

**Comment by Hedaja** [comment]
> Let's have two methods, one to empty the datalayers (but keep them), and the other on to delete the layers and data.

Awesome
that's exactly what I was hoping that the button would do.
I have a map with over 50 filled layers and want to make it a blueprint file, therefore deleting all the data within those layers =)

**Comment by davidbgk** [comment]
@yohanboniface so we would have both `Empty map` (removing layers completely) and `Empty all layers` (erasing inner data but keeping the structure)?

**Comment by yohanboniface** [comment]
> so we would have both Empty map (removing layers completely) and Empty all layers (erasing inner data but keeping the structure)?

Yes! Maybe "Clear data" / "Remove layers" ?
