### ISSUE TITLE
Search for feature (enhancement)

### ISSUE THREAD

**Issue by stevage** [umap-project/umap#208]
I've just discovered this project - looks awesome. Has there been any discussion of having a search box that allows searching for a string in any field of any object? 

Currently you can "filter", but that works on the "name" of an object only - it doesn't search any other fields.

(Répondez en français si vous préferez...)

**Comment by yohanboniface** [comment]
Not sure about previous issues on this topic, but that is discussed and requested from time to time.

I agree that this would be a nice enhancement. Some thoughts:

- at UI level, this needs to integrate in a way or another with place seach, so users understand when they search for places or when they search for current map features; I'd like to rethink the search bar anyway, because it's to much hidden now, while it's a core need

- this should also work when there are 3000 objects on the map (so the actual pattern of looping would not scale I think if we'd also look on every fields)

- not sure looking at all objects fields is really the best option, maybe keeping the option to define which fields to search on (even if less user friendly for the map administrator) is more scalable

- note that the current "filter" feature can be customized to search on custom fields (so if you want to search on say fields "foo" and "bar" you would put "foo,bar" in the option); for this, you need to go on map settings (gear) => default properties => last field (and now I see that this field is missing a label :/)

**Comment by stevage** [comment]
>at UI level, this needs to integrate in a way or another with place seach, so users understand when they search for places or when they search for current map features;

Yup. I work on [National Map](nationalmap.gov.au). We have exactly [the same issue](https://github.com/TerriaJS/terriajs/issues/647). Currently we have one search that does both location and data, but it's confusing. 

>not sure looking at all objects fields is really the best option

If you're showing the results as "search  results", ordered by relevance then I think the UX is fine. So results in important fields like "name" appear before more obscure fields.

>note that the current "filter" feature can be customized to search on custom fields

That's exciting! Very hard to find, but that definitely solves my immediate need. The UX of this "default properties" section is a bit...unintuitive. This option definitely doesn't seem to belong there - maybe under "user interface options" would make more sense.

(Incidentally, I accidentally entered my search fields "name,description" under "Property to use for sorting features" and it worked just fine there. :))

**Comment by yohanboniface** [comment]
> (Incidentally, I accidentally entered my search fields "name,description" under "Property to use for 
> sorting features" and it worked just fine there. :))

Yep, that's tried as fallback https://github.com/umap-project/Leaflet.Storage/blob/master/src/js/leaflet.storage.controls.js#L550 :)

> The UX of this "default properties" section is a bit...unintuitive. This option definitely doesn't seem 
> to belong there - maybe under "user interface options" would make more sense.

Yes! The UI needs a bit of love. I've been iterating over it for time, but adding and adding more options and feature we came to the point where it needs a bigger revamping. Plus take in mind that the next version will support MultiPolygon and MultiPolyline, and thus actions like split a multi or add a shape in a multi, etc., which will charge again the UI.
