### ISSUE TITLE
Add a Draft status

### ISSUE THREAD

**Issue by yohanboniface** [umap-project/umap#2207]
Suggestion from @Binnette: add a way to distinguish quality maps from the mass.

One option may be to have a draft status, and each map would first saved in this status, and editors would explicitly "publish" a map.

That could be a new boolean property `draft=true/false`, or a new value for `share_status=draft`, and in this case the map would react as for `share_status=public`: it would not be listed in the home/search, and would not be indexable by bots.

**Comment by Binnette** [comment]
On one hand, I don't want to see maps that are just like "user create umap account, create a map, draw a circle and quit umap definitively". Because this kind of map is not interesting for me.

On the other hand, if we add draft/published status, we have to "encourage" users to publish/realese their map when they save them, etc. Otherwise a lot of maps will stay in draft status...

Maybe a good way to see if a map is "interesting" is to look the version number of the map. If the map was edited 30 times, probably the user really works on his map and try to make it useful and pretty.

So maybe in the "featured maps", we should propose categories:

- Most starred maps
- Most edited maps
- Most viewed maps (no tracker today)

And also add keyword or research like: hiking, Paris, etc.

**Comment by yohanboniface** [comment]
In my idea, a map in Draft status is only visible by the owner/editor, so this should encourage users to publish when they need to share (though not all maps are made to be shared).

**Comment by Aurelie-Jallut** [comment]
I like this draft idea because it makes it easier to identify when the card is published and how: public / private.

The risk is that a lot of interesting cards will remain in the draft?

(I'd add that it motivates me to add a title and improve my card when I know it's appearing in searches).

**Comment by yohanboniface** [comment]
My suggestion is to add two values to the `share_status` field, so the final values would be:

- (DRAFT, _("Draft")),
- (PUBLIC, _("Everyone (public)")),
- (OPEN, _("Anyone with link")),
- (PRIVATE, _("Editors and team only")),
- (BLOCKED, _("Blocked")),
- (DELETED, _("Deleted")),

The downside of this option (vs another field) is that a user cannot set the share_status without removing the drag state (which I think is very minor), and in the case we restore a deleted map, we'll have lost the previous `share_status`, but in this case I'd suggest that restoring a deleted map always but the map back to `draft`.

So the smallest step to deploy this would keep the share status where it is now (but "deleted "would not appear in the list):

![Image](https://github.com/user-attachments/assets/8aa7b4de-3a4c-4a64-ab2c-116d7ddc44e6)

Is that ok or do we want something else ? Maybe changing the "Save" button to "Save draft" while the map is draft ? 

@Aurelie-Jallut @davidbgk thoughts ?

This will be needed to deploy with S3 storage, and in place of the purgatory system.

**Comment by davidbgk** [comment]
How is it related to S3 storage?

**Comment by yohanboniface** [comment]
Because if we deploy with a S3 storage, we'll lose the purgatory, so the deleted maps will be deleted for real, without backup.
