### ISSUE TITLE
dev-doc request: Describe a setup to hack on the frontend code

### ISSUE THREAD

**Issue by thoka** [umap-project/umap#254]
Unfortunately I am not familiar with software stack used by umap. 
Please provide some pointers about setting up a development environment. 

Would a (github) wiki page be a good place to collect this information?

**Comment by thoka** [comment]
Does http://stackoverflow.com/questions/13179778/maintaining-3rd-party-django-apps-as-git-submodules include some valuable advise regarding this question ?

**Comment by yohanboniface** [comment]
Yeah, the stack is not easy to setup if you are not familiar with python + django + git.
I'll try to set something up in the wiki.
Basically, if you only want to hack on the frontend, you can clone Leaflet.Storage where you want, and then tell django load it there instead of the version bundled with django-leaflet-storage. For this, you can use this setting in your local settings:
```
STATICFILES_DIRS = (
    ("storage", "/path/to/Leaflet.Storage/"),
) + STATICFILES_DIRS

```
Same for any other frontend library you want to work on. "storage" here is basically the first path after "static" in the Leaflet.Storage static URL.

Pass by on IRC if you need live help :)

**Comment by yohanboniface** [comment]
There is since then a "Contribute" page on the documentation: https://umap-project.readthedocs.io/en/master/contributing/#development-on-ubuntu
