### ISSUE TITLE
API key required overlay on maps

### ISSUE THREAD

**Issue by RosscoMac** [umap-project/umap#455]
Hi there,

I've been using Umap on my blog site since last year and all of a sudden the maps are now overlayed with "API key required". I can't work out why, I thought this was an open source project meaning it was free? Does anyone know how to fix this?

Thanks for your help!

**Comment by VladimirSlavik** [comment]
Hi RosscoMac, that is a misunderstanding.

Umap is what allows custom points, lines and all that. But these are displayed over a map in the background. There is a wide choice of these background maps, coming from various providers, and some of them require a contract for higher traffic. Your blog is probably very popular (congrats!) - so your domain exceeded the free quota for the particular map background and got "api key required" images instead of the map background. (Alternatively, it is possible that the map provider changed terms of use.)

You can "fix" that by changing the background map to something else. Do your homework to find out where each background comes from... Some are available free of charge. It might be also possible to purchase an api key for the particular background that you want - just make sure you can actually use it with umap!

Please do note that umap is indeed free to get and use, and raw openstreetmap data too. It's the 3rd party providers that charge for the traffic when serving the images that actually make the map usable in browser. They are neither umap, openstreetmap, you or me :)

Hope this explains your problem!

**Comment by RosscoMac** [comment]
Hi Vladimir, thanks for getting back to me, and apologies for taking so long to reply!

I have been using OpenCycleMaps and managed to sign up for an API key from there but I'm really unsure how I go about implementing that in Umap to get rid of the overlay.

Are you able to explain to me where I enter this key in Umap? Or direct me to a FAQ that explains it?

Thanks!

**Comment by VladimirSlavik** [comment]
Hi, sorry, I am not able to do so without actually taking my time to learn about the stuff more than just the general outlines...

**Comment by yohanboniface** [comment]
Fixed on French servers as far as I can see.
