### ISSUE TITLE
404 on login

### ISSUE THREAD

**Issue by kieppie** [umap-project/umap#502]
when logging in to http://umap.openstreetmap.fr/en/, get a 404 when logging via GitHub ID

**Comment by yohanboniface** [comment]
Try with https://umap.openstreetmap.fr/en/.

**Comment by kieppie** [comment]
nope. redirects to:

http://umap.openstreetmap.fr/complete/?error=redirect_uri_mismatch&error_description=The+redirect_uri+MUST+match+the+registered+callback+URL+for+this+application.&error_uri=https%3A%2F%2Fdeveloper.github.com%2Fv3%2Foauth%2F%23redirect-uri-mismatch&state=$SOMEHASH

**Comment by stevage** [comment]
Still broken for me.

**Comment by yohanboniface** [comment]
Still working for me ;)

I'll need more details to be able to help. Also check out your browser extensions.

**Comment by stevage** [comment]
Ah, that's interesting. In Chrome incognito mode (disables most extensions) it worked. So yeah, presumably one of my extensions is doing...something.

**Comment by stevage** [comment]
Huh, actually no. Disabling all my extensions didn't work. But if I log out of Github, then uMap's Github login page works (it shows the login screen and I can log in), but as soon as the login completes, it goes to the 404 page. (Same in incognito mode).

What other info would help debug this?

**Comment by yohanboniface** [comment]
I don't have Chrome, but I works on Chromium 61.0.3163.79 (Developer Build) (64-bit) here.

Can you paste the final 404 URL?

**Comment by stevage** [comment]
https://umap.openstreetmap.fr/complete/?error=redirect_uri_mismatch&error_description=The+redirect_uri+MUST+match+the+registered+callback+URL+for+this+application.&error_uri=https%3A%2F%2Fdeveloper.github.com%2Fv3%2Foauth%2F%23redirect-uri-mismatch&state=0ZoEOHoz8lkcqMXSbn1G8PB7YhOXeZmm

**Comment by yohanboniface** [comment]
Can you log out from Github, click on Github icon on uMap, and copy-paste the URL you ends with on Github (before filling any form)?

**Comment by stevage** [comment]
https://github.com/login?client_id=c976781d7d009804978f&return_to=%2Flogin%2Foauth%2Fauthorize%3Fclient_id%3Dc976781d7d009804978f%26redirect_uri%3Dhttps%253A%252F%252Fumap.openstreetmap.fr%252Fcomplete%252Fgithub%252F%253Fredirect_state%253D0ZoEOHoz8lkcqMXSbn1G8PB7YhOXeZmm%26response_type%3Dcode%26scope%3Duser%253Aemail%26state%3D0ZoEOHoz8lkcqMXSbn1G8PB7YhOXeZmm

**Comment by yohanboniface** [comment]
Yes, double encoding is expected: it's a URL passed as parameter.

Sounds like the usual http/https story. Sadly it's not easy to force https on umap, because this will prevent user to use non https URLs for icons or remote data or import data, which is not very friendly, given the scope of uMap which is something like "make map easy for *non technical* people".

So try with http:// instead of https://, and if it does not work, it may be that Chrome is forcing you to use https, which is for good, but it's not always good.

**Comment by spectras** [comment]
Hit with the same issue.
I can confirm this is due to http/https mismatch.

* Clicking the github link from https://umap.openstreetmap.fr/en/ gives a 404 (with the URL mismatch message in the url)
* Clicking the github link from http://umap.openstreetmap.fr/en/ works.

**Comment by akien-mga** [comment]
For the reference, I can confirm that the issue is still valid today when using the GitHub identification. (Firefox Nightly, with DuckDuckGo Privacy Essentials which enforces HTTPS when available). Disabling the extension and going to the HTTP variant allows to log in.

**Comment by jpiesing** [comment]
It's still the case today - having found this issue, I manually edited the URL to change https to http and login worked.

**Comment by yohanboniface** [comment]
We switched Github to https now.

**Comment by FFMbyBicycle** [comment]
Thanks!

Sadly I cannot login for some weeks now, regardless of using http or https :cry: I can reproduce it every time using a standard Chromium 114 (Arch Linux) in private browsing mode and multiple Firefox instances with and without add-ons:

https://github.com/umap-project/umap/assets/74880272/1224ac9c-bcb2-4b23-87f6-2b36932be046

Using http instead of https results in the common 404 error, which should be fine due to the latest changes. I would like to backup all my maps and re-import them using another auth method, but I will have to login at least once for this...:smile:

**Comment by yohanboniface** [comment]
That's another error, I guess due to username conflict (see for example #1106 ). What's your github username ?

**Comment by yohanboniface** [comment]
That username was used with your Twitter login. I've renamed it, so you can use Github now.

**Comment by FFMbyBicycle** [comment]
Whoops, thanks a lot! That Twitter hustle did cause some confusion, sorry for that.
