### ISSUE TITLE
Unable to open the tilelayers list when control is set to "never"

### ISSUE THREAD

**Issue by francoisfogel** [umap-project/umap#512]
Hi,
I am working on my first project since yesterday ([https://umap.openstreetmap.fr/fr/map/ressources-jeune-public_165556#6/47.279/7.207]), and I am experimenting frozen pages,  and un-responding features in the interface (as the "Change background map" button).
Tested on Chrome and Firefox, no proxy, optical fiber connection, with and without ad blockers (Ghostery).
Any idea ?
Thanks for your help

**Comment by yohanboniface** [comment]
Oh, I see: this is because you've set the "tilelayers" to never appear on the map. So it's hidden from the left toolbar, thus… not added to the map when the right toolbar when to open it. Gasp.

I'll fix this for next release, in the meantime, only option si to let the tilelayer as visible or hidden (but not set to "never").

Thanks for your report!

**Comment by francoisfogel** [comment]
Great, Yohan. Many thanks for being so helpful.

**Comment by francoisfogel** [comment]
Sorry. This problem of frozen pages still happens when I try to edit a polygon, either by the contextual icon, or by the right menu.
So, I have 1 layer, with imported data (the regional boundaries of France). When I try to edit one region, it crashes. 
I think it comes from the volume of the data I imported from OSM boundaries (21 Mo uncompressed). Could an unreasonable number of objects be a source of trouble ?
Thanks, again
