### ISSUE TITLE
Embed Javascript into the map?

### ISSUE THREAD

**Issue by JamesNall** [umap-project/umap#596]
Is it possible to embed / implement javascript into the map itself? I'm planing to host my own instance of umap and add Google Analystics to the map so that I'm able to track the number of users. Is that somehow possible already or can this be added as a feature?

Thanks!

**Comment by yohanboniface** [comment]
@JamesNall yes, you can override the `content_footer.html` template and put your JS code inside it.
See https://github.com/umap-project/umap/blob/prepare-1.0/docs/custom.md for how to customize a uMap install.
Consider wayting for the 1.0 to be out (hopefully soon, WIP), because the customization will be a bit easier.

Side note: use https://matomo.org/ not G^Evil Analytics, per respect for your users ;)

**Comment by JamesNall** [comment]
Thanks! Could you also tell me where I need to specify the map to load the content_footer.html file? Is there some option in the local.py or uwsgi.ini file?

And I never heard of Matomo before. Thank you very much for that suggestion!

**Comment by yohanboniface** [comment]
If you are using the current release (pre 1.0), you need to do something like this to load your templates and statics dirs:

https://github.com/etalab/cartes.data.gouv.fr/blob/3a705554bf032d21e6fbac5b2d05f1a7afce8a51/local.py#L29-L34

Otherwise, follow the doc in  https://github.com/umap-project/umap/blob/master/docs/custom.md

**Comment by Binnette** [comment]
No more question. I close this ticket. Feel free to reopen it if needed.
