### ISSUE TITLE
localisation visualisée de manière multicritères / localisation visualized in a multicriteria manner

### ISSUE THREAD

**Issue by yohanboniface** [umap-project/umap#60]
Originally reported by: **Anonymous**

---

Il serait très utile de permettre d'associer aux géolocalisations d'une même couche/layer (point, ligne, zone) N critères (par exemple couleur et forme) qui diffèrent pour N-1 d'entre eux (par exemple les points peuvent être tous de la même couleur mais de forme différente, ou de même forme mais tous de la même couleur). Cela permettra de repérer visuellement donc rapidement dans une couche les points correspondants à des critères particuliers.

Par exemple, dans le cas d'une carte gérant des bars et des restaurants, une couche gèrera les bars (avec des localisations en forme de rond), une autre les restaurants (avec des localisation en forme de carré), et la couleur permettra de distinguer les restaurants chers (rouge) de ceux qui sont abordables (bleu).

[It would be very useful to allow to associate to geolocations of a same layer (point, line, area) N criterias (for example color and shape) which differ for N-1 of them (for example the points can be all of the same color but with different shapes, or same shape but with different colors). It would allow to visually and so faster identify into a layer the points corresponding to several specific criterias.

For example, in the case of a map managing pubs and restaurants, a layer will manage pubs (with localisations as circle shape), while another one will manage restaurants (with localisation as pin shape), and the color will distinguish the restaurants which are expensive (red) from this who are affordable (blue).]
- Fil.

---
- Bitbucket: https://bitbucket.org/yohanboniface/umap/issue/60

**Comment by PhilLAL** [comment]
I think the logic would we broken since an information of the same kind should not be disseminated into several dimensions.
Cheap or expensive pub are only the same kind of place (pubs) which can be classified into another dimension according to their prices.

Forcing to split a category/layer into several one each time a new category/layer is created will make it crazy to use. 
For example I create a category of pubs, then I create a category of prices in which I add a value (price) on a continuous positive scale (price for the cheaper beer) : 
-I have to split the pubs of the first category created into cheap and expensive, but I cannot create a category of pubs for 3€, 3,5€, 4€, 4,5€, 5€, ...
-Then I create a map of jazz pub, but I would like to use the data I entered for pub, because some of them are jazz pubs. So if I have to make a copy of pub data, and then my favorite pub change its cheaper beer price, I will have to change it into pub category and jazz category.
- Then I create a map of pub with rooftop, but I would like to use data entered for pub and jazz pub, ...
- Then I create a map of pub with snooker, but I would like to use data entered for pub, rooftop and jazz pub, ...

It seems there you can add properties in addition to name and description. Where can I find a doc to understand how to use. In particular, it could perhaps solve the issue if the same properties are available for each category (layer)

**Comment by VladimirSlavik** [comment]
Managing multiple dimensions offers many ways to slice the problem at hand, but always results in need for a type of "atomic group" for features, and [I believe] the right entity for that is a layer. Whether it's a layer in implementation or just labeled so in UI is perhaps a better question? I could imagine having "layers" presented in UI but being technically a sort of generator of Leaflet layers.

As a tangent, I use extensively an umap which has a binary criterion for all features and thus suffers from the same problem. I have observed that the way layers are presented to editor is a big hindrance. Expanding the list and scrolling each time I need to manipulate a whole layer is a huge pain.

**Comment by yohanboniface** [comment]
Closing in favor of #1433
