### ISSUE TITLE
TMS like Tilelayer

### ISSUE THREAD

**Issue by kleper** [umap-project/umap#645]
Can you add a tms like this https://tms.openstreetmap.co/mocoariomulato2/{zoom}/{x}/{-y}.png as Tilelayer in umap?

**Comment by yohanboniface** [comment]
Which umap instance are you refering to? :)

Is there a demo page somewhere?

Note: you can just add a custom background in your map anyway.

**Comment by kleper** [comment]
I am refering to this instance: https://umap.openstreetmap.co/es/
When I put this theme as a tilelayer with the coordinate -and it generates an error that I have not been able to debug and it does not let me choose any tilelayer on the maps.

**Comment by yohanboniface** [comment]
Ah, TMS option in the uMap admin is not available in the version that the umap.openstreetmap.co instance is running (0.8.3).
It has been added since then, and it will be in the 1.0.0 release.
Note: umap.openstreetmap.fr uses the RC of the 1.0.0.

So you need to either wait for the 1.0.0 to be released, or upgrade to the latest 1.0.0-rc. See https://umap-project.readthedocs.io/en/latest/changelog/#upgrading-to-10
