### ISSUE TITLE
Where can I find the Privacy Police?

### ISSUE THREAD

**Issue by webkarli** [umap-project/umap#646]
Where can I find the Privacy Policy for umap?

**Comment by robinmetral** [comment]
Good question @webkarli :slightly_smiling_face: 

Since uMap is in under [WTFPL](https://en.wikipedia.org/wiki/WTFPL) I think the Privacy Policy depends on the specific uMap instance you're using.

If you're thinking of https://umap.openstreetmap.fr, I couldn't find specific privacy information but you might want to [get in touch](http://www.openstreetmap.fr/contact/) with the French OpenStreetMap association which hosts the instance.

**Comment by robinmetral** [comment]
Feel free to lobby the FOSSGIS to host a uMap instance :slightly_smiling_face: 

uMap on openstreetmap.fr is actually multilingual, only the about/help aren't. Another possible way to find out about their privacy policy could be to write to the [official uMap mailing list](https://lists.openstreetmap.org/listinfo/umap).

Good luck!

**Comment by HDValentin** [comment]
Since openstreetmap.fr is driven by Openstreetmap.org I have linket to their privacy policy https://wiki.osmfoundation.org/wiki/Privacy_Policy

**Comment by althio** [comment]
thanks @webkarli @robinmetral @HDValentin for your questions and help here

>> @webkarli: Where can I find the Privacy Policy for umap?

> @robinmetral: If you're thinking of https://umap.openstreetmap.fr, I couldn't find specific privacy information

Indeed, there is non published privacy policy at the moment for umap.openstreetmap.fr (or *.openstreetmap.fr)
We will work on it, tracking progress at https://github.com/osm-fr/infrastructure/issues/93

> @robinmetral: I think the Privacy Policy depends on the specific uMap instance you're using.

I agree the privacy policy is not part of the tool itself, but is dependent of the host.
(And this issue #646 might be closed)

**Comment by Binnette** [comment]
I close the issue as suggested.
