### ISSUE TITLE
Google My Maps to uMap

### ISSUE THREAD

**Issue by Luen** [umap-project/umap#649]
I'm currently in the process of changing from Google My Maps to uMap. 
When importing from MyMaps (KML file export) the layers and icons are not coming across. Also hidden layers are visible.  
Here's an example of a map I've exported and imported into uMap.
https://drive.google.com/open?id=1COxEDptfz4uNU3v0BK4UqCACj7Q&usp=sharing

Is this something that will be supported in the future?

**Comment by yohanboniface** [comment]
uMap uses https://github.com/mapbox/togeojson/ to convert KML, so we more or less do what this lib can do.
I'll have a look anyway to see what we can do to make this import smoother.

**Comment by Luen** [comment]
@yohanboniface Thank you.

**Comment by tuxor1337** [comment]
I had a look into the output of Google My Maps (GMM) and at least for the layers, it would be necessary to consider the `<folder>` tags which are not supported by togeojson: https://github.com/mapbox/togeojson/issues/64

For the icons, GMM chooses the style ids in such a way that color and shape can be extracted from it: The id format is `icon-<shape_id>-<hexcolor>-labelson`. Of course, not all icons in GMM can be expected to have corresponding icons in umap - especially because the set of available icons can differ from instance to instance. We could host a reference collection of icons corresponding to the GMM icons somewhere and link to them via the icon URL feature of umap.

Actually, if you are a developer and you are interested in this issue, I would suggest writing a standalone conversion tool from GMM output to the umap json format. This will already be extremely useful in itself. Moreover, once we have this it should be doable to integrate similar functionality into umap.

**Comment by numeropi** [comment]
I had a similar problem importing a .kml that came from GAFAM MyMaps into Umap and the description wasn't well imported...
ex:
<description><![CDATA[Your HTML content here]]></description>

in umap it got imported as: [object Object] 

(see screnshot)
![imagen](https://github.com/umap-project/umap/assets/56868560/115fa3e3-1136-49b7-bbfe-0e1d3a0db62f)

**Comment by iago-pssjd** [comment]
What a pitty this issue was closed by github-actions. I would say it might worth to open an issue to https://github.com/mapbox/togeojson/, but it has not been updated since more than one year ago. Do you know if there is any under development fork? Or any other equivalent tool which could replace that in umap?

**Comment by yohanboniface** [comment]
What's your issue precisely ? There is one specific for the HTML description problem: #1481. Or is it something else in your case ?

**Comment by iago-pssjd** [comment]
Thanks for the reference! No issue in particular, just the things commented here, assuming they have not being solved (layers and icons, <folder> tags [and description])

**Comment by MrKuip** [comment]
see https://github.com/umap-project/umap/issues/538#issuecomment-4812945583
