### ISSUE TITLE
Change color of all pins

### ISSUE THREAD

**Issue by HDValentin** [umap-project/umap#664]
It is a feature request: changing colors and signs for all pins on a map.
A function that changes the color and the sign with one click.

**Comment by TZornG** [comment]
Maybe I'm telling you something you are already aware of, but maybe this already solves your particular problem, especially since you talk about "all" and not "some" pins. There is a style hierarchy map - data layer - individual object. So if you don't set color and style on an individual object it takes the color from the data layer or map. To change the color of all pins, remove the individual color setting (admittedly, you cannot do that in one go I think) and set a different color on layer or map level.

**Comment by HDValentin** [comment]
Thank you for mention. Changing all helps a bit. But it is not the solution.
The best would be a function: change the color of pins with color #xxxxxx to color #yyyyyy, and switch the symbol to xyz.

**Comment by M-Rick** [comment]
Maybe what you are speaking about is to prepare a dataset in which everything would be ready when you import in uMap?
I explained in here how to proceed by striking with the hidden "_umap_options" field.
But you will have to use a GIS in order to accomplish this.
https://github.com/umap-project/umap/issues/494

If by doing this we could personalise the markers icons as well, this would be fantastic!
