### ISSUE TITLE
wrong local messages in map pages (home is OK)

### ISSUE THREAD

**Issue by AleZena** [umap-project/umap#671]
Hi,
in a new installation we can see the home page in the right localization, but the other pages (that using django.po) are shown in english.

**Comment by Binnette** [comment]
Hi @AleZena, are you talking about Italian localization?

Can you please translate the 6 missing strings?
https://www.transifex.com/yohanboniface/umap/translate/#it

Since you do not provide any screenshot, i don't know which string to check in transifex. So please can you review in transifex if the Italian localizations are ok?

**Comment by Binnette** [comment]
Ok, by visiting https://umap.openstreetmap.fr/it/about/ I found this:
![image](https://user-images.githubusercontent.com/6597721/74785628-01b8e080-52ab-11ea-809a-4f25634c6387.png)

This is not in Italian. By looking to Transifex this is one of the 6 untranslated strings i was talking about.

So can an Italian speaker help us on https://www.transifex.com/yohanboniface/umap/translate/#it ?

**Comment by Binnette** [comment]
Hi @piersoft, @airon90, @lucacorsato, @mircozorzo

Since you are part of the [Italian uMap translation team](https://www.transifex.com/yohanboniface/teams/2766/it/), can you please translate the 6 [untranslated strings](https://www.transifex.com/yohanboniface/umap/translate/#it)?

Also please consider reviewing other Italian strings. It will be much appreciated. :+1:

Have a nice day.

**Comment by Binnette** [comment]
Thanks a lot @mircozorzo & @piersoft :+1: 

I will update my PR #744 then.

@AleZena : i'm closing this issue. Please follow my PR to get news.
