### ISSUE TITLE
Invalid geojson

### ISSUE THREAD

**Issue by vinber** [umap-project/umap#685]
Steps to reproduce:

- export umap in GeoJson,
- check it : http://geojsonlint.com/
- it says "Polygons and MultiPolygons should follow the right-hand rule"
- if you use first Mapster (https://mapster.me/right-hand-rule-geojson-fixer/), geojsonlint is happy

**Comment by yohanboniface** [comment]
Not sure this has to be fixed in uMap, certainly in Leaflet. But I don't think I'll have energy to takle this myself :( 

cf https://github.com/Leaflet/Leaflet/issues/5384 and https://github.com/Leaflet/Leaflet/issues/3498

Also note that, while the spec clearly states that rings must follow the right-hand rule, I don't know any parser that will break on that (but I may miss one).

Workaround: https://mapster.me/right-hand-rule-geojson-fixer/
