### ISSUE TITLE
Add CyclOSM map

### ISSUE THREAD

**Issue by Florimondable** [umap-project/umap#712]
Hello, can you add the bicycle map CyclOSM in the possible map list ?

Project : https://github.com/cyclosm/cyclosm-cartocss-style/
Tiles from : https://dev.{s}.tile.openstreetmap.fr/cyclosm/{z}/{x}/{y}.png

**Comment by Binnette** [comment]
@Florimondable, @lamyseba: Since your request, it seems that CyclOSM has been added on https://umap.openstreetmap.fr
![image](https://user-images.githubusercontent.com/6597721/74784094-7558ee80-52a7-11ea-8795-8e5cafa006cb.png)

If you are not using the ".fr" version (https://umap.openstreetmap.fr), for exemple https://umap.openstreetmap.de, you will have to contact the administrator of https://www.openstreetmap.de

Note: adding tiles is a configuration done directly on server (no code need to be changed), so i'm closing this issue. Feel free to reopen it if needed.

**Comment by lamyseba** [comment]
Saw that, great! Great job that this map is now available on umap! 


Sébastien Lamy
