### ISSUE TITLE
Programmer

### ISSUE THREAD

**Issue by 3TS5f4AGri6TRr** [umap-project/umap#750]
Our company is trying to de-Google, and we are in the process of converting to Umap and OSM. But we need a bit of help from a developer to add a couple of features. If anyone is willing to help, we are happy to pay.

**Comment by Binnette** [comment]
Hi @3TS5f4AGri6TRr, fill free to submit new "feature request" in https://github.com/umap-project/umap/issues Please put only one "feature request" by issue. 

If you want to hire OSM pro, please have a look here:
- https://wiki.openstreetmap.org/wiki/Commercial_OSM_Software_and_Services
- https://lists.openstreetmap.org/listinfo/osm-professional

Since this "issue" is not a "feature request" or an uMap bug. I'm closing it.

Have a nice day.
