### ISSUE TITLE
Update Polish translations

### ISSUE THREAD

**Issue by maro-21** [umap-project/umap#758]
Hello, could you update the translations? I've recently translated all the missing strings in Polish and also corrected all of them. But anyways, looks like translations haven't been updating for at least a year.

**Comment by Binnette** [comment]
Hi @maro-21, i'm currently working on it, see #744..., but you're gonna help me 😉 

Can you please tell me if we need language "Polish (Poland)" ? (we already have 100% for "Polish")

See the two languages here:

- 100 % translated in "[Polish](https://www.transifex.com/openstreetmap/umap/language/pl/)"
- 71 % translated in "[Polish (Poland)](https://www.transifex.com/openstreetmap/umap/language/pl_PL/)"

Please have a look to the transifex strings in those 2 languages and tell me if you see a difference.

Do you think I can remove the language "Polish (Poland)"?

Note there are only those 2 languages available in Transifex for "Polish":
![image](https://user-images.githubusercontent.com/6597721/75779764-83ecde80-5d5a-11ea-9489-c7dd5dd9de81.png)

@rafalrusin, @TomaszNycz, @RicoElectrico, @grzebo, @mkalisz, @rootolf, @sq7obj, since you are part of the uMap Polish translation team, I'am also really interestedby your point of view on my questions.

**Comment by maro-21** [comment]
Yes, "Polish (Poland)" is a duplicate and should be deleted.

**Comment by Binnette** [comment]
Thanks @maro-21, i "double check" translations in "pt_PT" and in fact this is just plain english without any Polish translation. So I removed it from Transifex.

BTW, my Pull requet #744 is now merged. So you will get Polish translations in the next uMap release.

I am closing this ticket, feel free to reopen it if needed.

**Comment by mkalisz** [comment]
Hey guys, its really nice to be a part of some kind of group but i dont
know why im in this conversation :)

wt., 3 mar 2020 o 14:52 maro-21 <notifications@github.com> napisał(a):
