### ISSUE TITLE
Difficulty in loading Overpass to uMap

### ISSUE THREAD

**Issue by mapbeks** [umap-project/umap#786]
I followed doing this link and it seems that it wasnt able to show the data from OSM.

http://www.mappa-mercia.org/2014/09/creating-an-always-up-to-date-map.html

Other than that, I also tried copy-pasting the same link shown and followed the data type to osm and ticking dynamic.

These are the links I tried using. on my map to pull out the overpass query
Im trying to pull out schools

http://overpass-api.de/api/interpreter?data=[out:json][timeout:25];(node["amenity"="school”]({south},{west},{north},{east});way["amenity"="school”]({south},{west},{north},{east});relation["amenity"="school”]({south},{west},{north},{east}););out;>;out skel qt; 

Hopefully you can help me. 

Lastly, I. was trying to explore umap if I can only load overpass turbo bounded only in a specific bbox but would be nice to find out first how to load all the needed data then limiting it to a specific  bbox. 

Thanks in advance

**Comment by Binnette** [comment]
Hi, can you please add a link to your umap project here?
This way, i can test it easily.

**Comment by jamescr** [comment]
I followed the same [link](http://www.mappa-mercia.org/2014/09/creating-an-always-up-to-date-map.html) and also I'm unable to show data from OSM.  

Link to the umap: https://umap.openstreetmap.fr/es/map/hidrantes-de-alajuela_489052#16/10.0163/-84.2186. 

Overpass query is:

`http://overpass-api.de/api/interpreter?data=[out:json][timeout:25];(node["emergency"="fire_hydrant"]({south},{west},{north},{east}););out body;>;out skel qt;`

**Comment by carlbacker** [comment]
Hi @mapbeks , I solved this the same way as @jamescr so I hope it worked for you too.

Custom bbox is also easily done in overpass, but most often the same result is easier with geoname coded areas such as `amenity=post_box IN "Rio de Janeiro"` or `amenity=library IN Kenya` through the wizard.

But adding custom bbox values directly to query parameters looks like this
(_comma-separated point-decimal degrees in order of_: `S lat, W lon, N lat, E lon` ) : 

> `[out:json][timeout:25][bbox:50.6,7.0,50.8,7.3];`

I have tried a uMap style URL export with this in a query, as a dynamic layer in a testing uMap and it worked perfectly.

There are other ways of adding the bbox in an overpass URL, such as a separate variable in the URL call, which is more programmable. More [details in Overpass wiki](https://wiki.openstreetmap.org/wiki/Overpass_API/Overpass_QL#Global_bounding_box_.28bbox.29).

**Sidenote:**
Since you are working with school data, which is often areas/polygons that uMap doesn't always handle well in low zoom levels and features like cluster and icons, have a look at showing [polygons as centroid nodes](https://github.com/umap-project/umap/issues/802#issuecomment-739640622) instead.
