### ISSUE TITLE
Cant change ownership of current map

### ISSUE THREAD

**Issue by myleneboyrie-tanaguru** [umap-project/umap#803]
Hey, I have a map linked to my account, and I want to give the ownership to another user. I got a red error message « Une erreur est survenue » after trying to switch permissions... Any idea how to change ownership ?

[The map is this one](https://umap.openstreetmap.fr/fr/map/les-pep-grand-oise_453155#10/49.3810/2.5186)

I want to give ownership to PEPGO user (currently editor on the map).

**Comment by Lukas458** [comment]
Okay, thanks for your issue.

- Please at first, make sure that you are the actual owner of the map. Normally this is clear but rather preventing misunderstandings.

Maybe it works when you do the following:
- Go the maps permissions (key-symbol), but first, type your own username in the field of "people who can edit the map". When you typed in your own name  click on it so that you see you are an editor (even though you still are the owner at the moment).
- After this, try again to change the map's owner.

Maybe try also this:
- Remove yourself from "people who can edit the map" again and make sure you are actually the owner of the map.
- Remove PEPGO from "people who can edit the map"
- Then try to make hin the map's owner.

**Comment by Binnette** [comment]
Hi, may be you can try to "clone" your map: https://wiki.openstreetmap.org/wiki/UMap/FAQ#How_to_clone_a_uMap_project.3F

**Comment by yohanboniface** [comment]
Should be fixed since today release. Please test and give feedback :)
