### ISSUE TITLE
chrome does not display side panel description when firefox does

### ISSUE THREAD

**Issue by Hugo-Trentesaux** [umap-project/umap#811]
I created a test map with µMap (https://framacarte.org/fr/map/test_79228#7/49.482/5.092) with a description in a side panel (zzzzzzzzz). I can see it in firefox but not in chromium.

![image](https://user-images.githubusercontent.com/18427584/85870764-c89afa80-b7cd-11ea-9350-7a19c82cdca1.png)

![image](https://user-images.githubusercontent.com/18427584/85870878-ef593100-b7cd-11ea-9a60-651fa9dafcae.png)

**Comment by yohanboniface** [comment]
Sorry, I missed that issue since then. As I can see, the template of the panel is for GeoRSS, so it does not read the description:
![image](https://github.com/umap-project/umap/assets/146023/2bc0fada-f716-4d8b-94e1-f9c7bb51adec)

Not sure why it showed up on Firefox, but maybe this was we others settings…
