### ISSUE TITLE
Disappearing Polygon Shapes On Closer Zoom 

### ISSUE THREAD

**Issue by Ethan777100** [umap-project/umap#815]
![uMap2](https://user-images.githubusercontent.com/49090166/86270699-38f6b100-bbfe-11ea-81a9-2d5aa1fa18fd.gif)

Watch the gif carefully - u will notice that my polygon rectangles will disappear after a prolonged period of moving ard in uMaps at the maximum zoom.

Currently on openstreetmap layer. but i dont think its a layer problem but a general uMaps problem

**Comment by Ethan777100** [comment]
bump

**Comment by yohanboniface** [comment]
@Ethan777100 thanks for the report, but we need more information in order to reproduce the issue and investigate.

Can you give a step by step to reproduce ?

Thanks

**Comment by Ilovepizzaa** [comment]
Hello Guys, I have exactly the same issue. Here some information to reproduce the bug : 
I navigate on my UMAP map (with a layer containing thousands of polygons)
I zoom and unzoom, and after few seconds a part of my polygons disappears just like if one "block" is not loading.
and after a moment it is the entire map that disappears... So I'm forced to refresh the entire map. and so on... 

I joined two screens of the problem. As you can see a part of the layer is missing on one of this two images... 

It is a very recurring problem... it has been months since I have this issue... And i know lot of people having this issue too... 

thanks in advance and have a nice week

![1](https://user-images.githubusercontent.com/72131738/94669811-07cb7100-0312-11eb-80aa-0dec80e30410.PNG)
![2](https://user-images.githubusercontent.com/72131738/94669816-09953480-0312-11eb-8830-056791325bfa.PNG)

**Comment by Ilovepizzaa** [comment]
up

**Comment by yohanboniface** [comment]
I link to a map to reproduce the issue would help

**Comment by yohanboniface** [comment]
Please reopen with a link to a map to reproduce the issue if still needed.
