### ISSUE TITLE
Localisation is locked when using it

### ISSUE THREAD

**Issue by Dirk71** [umap-project/umap#923]
Using the localisation feature could be more comfortable.

Now:
Enabling localisation locks the zoom level. I cannot zoom in or out while using localisation.

How it should be:
Enabling localisation shows the blue dot where my current location is and zooms close to it.
Zooming in and out is still possible. Moving into the map to another location is possible but after a certain while (e.g. 10 sec) the map will automatically center again to the current location (without changing the zoom level!).

**Comment by Gonzo360** [comment]
Exactly, because this is a center button but not a location button.. there should be the option to add a location only button, without centering..
Because now you can not zoom or move around because the screens goes back to the point when you pressed the ´location´ icon.. 
It would be good to either:
1) Be able to move around for free after pressing the icon.
or
2) Having two different buttons: One for the location to show where you are and another one for centering the screen based on your location.

Hopefully the request of Dirk71 is fixed :D

**Comment by Dionisos76** [comment]
I notice the same problem. I join this request and find that the solutions are relevant. It would be great to improve it.

Gonzo360 : Is it really fixed ? I don't find it.
